### ISSUE TITLE
Use REST API endpoint instead of admin-ajax.php

### ISSUE THREAD

**Issue by swissspidy** [hlashbrooke/Easy-Post-Embed-Code#1]
The oEmbed API endpoint already gives you the embed code for a specific post, respecting the `maxwidth` parameter.

Perhaps needs filtering to make sure it works for draft posts, but that shouldn't be a big deal.

Using the REST API instead of a custom `admin-ajax.php` endpoint makes the whole thing more future-proof.

**Comment by hlashbrooke** [comment]
That sounds good to me, but aren't the API endpoints not yet in core? In all honesty, I haven't actually worked with the REST API at all yet, so not sure what is involved in something like this. I don't expect it to be too tough though :)

**Comment by swissspidy** [comment]
The regular API endpoints aren't in core yet, but oEmbed is. The endpoint is available under the `oembed/1.0` namespace. `/wp-json/oembed/1.0/` lists the endpoint with all available parameters (`url`, `format`, `maxwidth`).

The JSON response includes a `html` property containing the blockquote + iframe embed code.

**Comment by hlashbrooke** [comment]
Sweet - will look into that for the next release as well :)
