### ISSUE TITLE
Live preview of the embed code

### ISSUE THREAD

**Issue by swissspidy** [hlashbrooke/Easy-Post-Embed-Code#2]
I think we've talked about this one before.

Displaying the iframe in the meta box on page load would be quite simple. The next step would be updating it using Ajax (or just JavaScript DOM manipulation) when changing the width / height text inputs.

Eventually, the iframe could be updated automatically. Customizer-style.

**Comment by hlashbrooke** [comment]
A live preview of the embed code would be great and definitely something Ii must add for v1.1 - I just haven't found time to work on it yet :p
